Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -1,54 +1,88 @@
-name: Pipeline Update
+name: Trigger SQL Pipeline Update
 
 on:
   push:
-    branches:
-      - main
+    branches: [ main ]
     paths:
-      - 'domain_1/**'
+      - 'domain_1/*.sql'
 
 jobs:
-  update_pipelines:
+  update-pipeline:
     runs-on: ubuntu-latest
     steps:
-      - name: Checkout code
-        uses: actions/checkout@v3
-        with:
-          fetch-depth: 0
+    - name: Checkout code
+      uses: actions/checkout@v3
+      with:
+        fetch-depth: 0
 
-      - name: Fetch Changed Files
-        run: |
-          git fetch origin
-          changed_files=$(git diff --name-only --diff-filter=d "${FIRST_COMMIT}" "${LAST_COMMIT}" | grep '^domain_1/.*\.sql$' || true)
-          echo "Changed files: $changed_files"
-          echo "CHANGED_FILES=${changed_files}" >> $GITHUB_ENV
+    - name: Load Configuration
+      id: load_config
+      run: |
+        DOMAIN_ID=$(grep '^domainid=' domain_1/config.txt | cut -d '=' -f 2)
+        HOST=$(grep '^host=' domain_1/config.txt | cut -d '=' -f 2)
+        echo "DOMAIN_ID=${DOMAIN_ID}" >> $GITHUB_ENV
+        echo "HOST=${HOST}" >> $GITHUB_ENV
 
-      - name: Get Pipelines
-        run: |
-          pipelines=$(curl -k --location "https://att-iwx-ci-cd.infoworks.technology/v3/domains/${DOMAIN_ID}/pipelines" \
-            --header "Authorization: Bearer ${TOKEN}")
-          echo "$pipelines" | jq -r '.result[] | "\(.name) \(.id)"' > pipelines.txt
+    - name: Fetch Token
+      id: fetch_token
+      run: |
+        TOKEN_RESPONSE=$(curl -k --silent --location "https://${{ env.HOST }}/v3/security/token/access" \
+          --header "Authorization: Basic ${{ secrets.REFRESH_TOKEN }}")
+        
+        # Print the full response for debugging
+        echo "Token API Response: $TOKEN_RESPONSE"
+        
+        # Extract the token
+        TOKEN=$(echo $TOKEN_RESPONSE | jq -r '.result.authentication_token')
+        echo "TOKEN=$TOKEN" >> $GITHUB_ENV
 
-      - name: Process Changed Files
-        run: |
-          for file in $CHANGED_FILES; do
-            pipeline_name=$(basename "$file" .sql)
-            pipeline_id=$(grep "$pipeline_name" pipelines.txt | awk '{print $2}')
+    - name: Determine Commit Range
+      id: determine_commits
+      run: |
+        firstCommit='${{ github.event.before }}'
+        lastCommit='${{ github.sha }}'
+        echo "FIRST_COMMIT=${firstCommit}" >> $GITHUB_ENV
+        echo "LAST_COMMIT=${lastCommit}" >> $GITHUB_ENV
 
-            if [ -n "$pipeline_id" ]; then
-              query=$(base64 < "$file")
-              create_response=$(curl -k --request POST \
-                --url "https://att-iwx-ci-cd.infoworks.technology/v3/domains/${DOMAIN_ID}/pipelines/$pipeline_id/versions" \
-                --header "Content-Type: application/json" \
-                --header "Authorization: Bearer ${TOKEN}" \
-                --data "{\"pipeline_id\": \"$pipeline_id\", \"type\": \"sql\", \"query\": \"$query\"}")
-              
-              pipeline_version_id=$(echo $create_response | jq -r '.result.id')
-              
-              curl -k --request POST \
-                --url "https://att-iwx-ci-cd.infoworks.technology/v3/domains/${DOMAIN_ID}/pipelines/$pipeline_id/versions/$pipeline_version_id/set-active" \
-                --header "Authorization: Bearer ${TOKEN}"
-            else
-              echo "Pipeline ID not found for $pipeline_name"
-            fi
-          done
+    - name: Get the list of changed SQL files
+      id: changed_files
+      run: |
+        git fetch origin
+        changed_files=$(git diff --name-only --diff-filter=d "${FIRST_COMMIT}" "${LAST_COMMIT}" | grep '^domain_1/.*\.sql$' || true)
+        echo "Changed files: $changed_files"
+        echo "CHANGED_FILES=${changed_files}" >> $GITHUB_ENV
+
+    - name: Fetch Pipeline IDs
+      id: fetch_pipeline_ids
+      run: |
+        pipelines=$(curl -k --location "https://${{ env.HOST }}/v3/domains/${{ env.DOMAIN_ID }}/pipelines" \
+          --header "Authorization: Bearer ${{ env.TOKEN }}")
+        echo "$pipelines" | jq -r '.result[] | "\(.name) \(.id)"' > pipelines.txt
+        cat pipelines.txt
+
+    - name: Process Changed Files
+      run: |
+        for file in ${{ env.CHANGED_FILES }}; do
+          pipeline_name=$(basename "$file" .sql)
+          echo $pipeline_name
+          pipeline_id=$(grep -w "$pipeline_name" pipelines.txt | awk '{print $2}')
+          echo $pipeline_id
+          if [ "$pipeline_id" != "null" ]; then
+            echo $file
+            query=$(base64 < "$file")
+            create_response=$(curl -k --request POST \
+              --url "https://${{ env.HOST }}/v3/domains/${{ env.DOMAIN_ID }}/pipelines/$pipeline_id/versions" \
+              --header "Content-Type: application/json" \
+              --header "Authorization: Bearer ${{ env.TOKEN }}" \
+              --data "{\"pipeline_id\": \"$pipeline_id\", \"type\": \"sql\", \"query\": \"$query\"}")
+            echo $create_response
+            
+            pipeline_version_id=$(echo $create_response | jq -r '.result.id')
+            
+            curl -k --request POST \
+              --url "https://${{ env.HOST }}/v3/domains/${{ env.DOMAIN_ID }}/pipelines/$pipeline_id/versions/$pipeline_version_id/set-active" \
+              --header "Authorization: Bearer ${{ env.TOKEN }}"
+          else
+            echo "Pipeline ID not found for $pipeline_name"
+          fi
+        done
